### ISSUE TITLE
[Refactoring] Translation and timezone implementation

### ISSUE THREAD

**Issue by Obihoernchen** [brusselopole/Worldopole#105]
## Expected Behavior
- Fix all annoying issues with translations and timezones once and for all

## Current Behavior
- Translation support is buggy and a pain to maintain #81 
- Some features don't even work
- Timezone is buggy in cron #90, we should write a dedicated load "class" for it
- duplicate code

## Possible Solution
- Have special loading classes for translations and timezone we can include everywhere it's needed
- refactor translation and pokemon files completely

### Have a translations.json file for each language
- with Key Value pairs
- so like the current one just seperate for each language
### Have a locale.loader.php
- This will load the language and can be included in each site which needs translation (so dashboard as well :D)
- This will load the specific language file + en language for fallback if the string isn't translated yet for new language
- Then it should be very easy for everybody to add new translations. Just copy paste the EN file and edit the strings
- There will be no merge conflicts with other languages or new features

---

### About pokedex.json
We should refactor pokelist_XX.json way more I think.
So we have one global pokedex.json with:
```json
{
  "typecolors": {
    "Grass":"#008000",
    "Poison":"#EE82EE",
    "Water":"#0000FF"
  },
  "1": {
    "max_cp":"1072",
    "max_pv":"82",
    "candy_id":"1",
    "quick_move":"Vine Whip",
    "charge_move":"Power Whip",
    "spawn_rate":0.0159,
    "candies":"25",
    "atk":"126",
    "def":"126",
    "stam":"90",
    "types":["Grass", "Poison"]
  },
  "2": { .., .. }
}
```
- Move Name and Description out, Users have to translate only this
- reference poke ID for candies instead of name --> no need to translate twice
- define type colors in own array
- instead of saving spawn_rate and rarity we should write a **function which translates rarity based on spawn_rate**. Then we just include translations for all rarities in translations.json.

### New file /XX/pokes.json
This will have: type translations, move translations and pokemon translations:
```json
{
  "moves": {"Tackle":"bla", "Quick Attack":"bla bla bla" },
  "types": {"Grass": "blablabla", "Water":"bla" },
  "1": {
    "name":"Bulbasaur",
    "description":"bla bla bla"
  }
  "2": { ... }
}
```
**Then merge both json files programmatically and replace moves and types with translations. Maybe resolve candy_id as well.**
This way we can update stats/optimal moves whatever and it will be translated automatically :wink:
All cronjobs need to touch pokedex.json only.

### File structure may look like this
```
└── core
    ├── json
    │   ├── pokedex.json
    │   └── locales
    │       ├── DE
    │       │   ├── pokes.json
    │       │   └── translations.json
    │       ├── EN
    │       │   ├── pokes.json
    │       │   └── translations.json
    │       └── FR
    │           ├── pokes.json
    │           └── translations.json
    └── process
        ├── locale.loader.php
        └── timezone.loader.php
```

**Comment by AL-dot-debug** [comment]
That's it :-) 

Let's go!

**Comment by SiteEffect** [comment]
First of all - Awesome <3

I do see the full potential in an actual cross-language and straight up working deployment of the website. We tackle multiple page issues with the translation part as well as counter some occasional troubles with the time class. I like the approach of the loading classes to just include them where needed.

We have to keep in mind to handle problems without available translation and assign the correct bonbon IDs to higher evolutions. Even more important is to keep the rarity/spawn-rate loader working with the changes.

**Comment by AL-dot-debug** [comment]
New translation system is up (need some debug probably) 
Still need to work on the new timezone

**Comment by Obihoernchen** [comment]
Guys see #108 :)
and #109 
and 59fefee6a44fea8f1519c972a4a41a334e81e9b2
yeaaaah #114 

## TODOs
- [X] Move spawn_rate into separate json and exclude it from git fd1df076647599b8bae47ff6ac03657369585ca3
- [X] Update Documentation: How to help translate...
- [X] ~~Cache all generated translation arrays to lower server load (use auto_ver)~~ @PoUpA will work on a client side js translation implementation so no need to work on server side caching
- [X] ~~Do not load locales and times on each aru.php request~~ it's ok
- [X] Improve pokemon json file splitting. Still a lot of dynamic data in pokes.json (see my first comment) #114
  - [X] Fix error on missing pokemon translations (see TODO in locale.loader.php) b887031f42ba4da06c7f5fea436f4bee2584ed78 07b6eb2168d1aedb053154ab66c7ad40cef779a8
  - [X] Fix and reenable rarity cron in `core/process/data.loader.php` once pokedex/pokes.json is final #114
  - [X] Use new json file in `core/cron/pokemon.cron.php` once pokedex/pokes.json is final #114
  - [X] Add german pokemon translation back once pokedex/pokes.json is final #114
- [X] Fix PHP warning: `PHP Warning:  Creating default object from empty value in .../core/process/locales.loader.php on line 75` #111 
- [X] Implement timezone.loader.php #109 
- [X] Use new loader classes in cronjob php scripts
- [X] Fix timezone not implemented in cron #90 
- [X] Make `core/process/aru.php` locale ready #81 
- [X] Fix dashboard `PHP Fatal error:  Cannot use object of type stdClass as array in .../core/js/dashboard.graph.js.php on line 49` Done: https://github.com/brusselopole/Worldopole/commit/29455c3f8528055ab7a06c64c15ce6012cd02f56

**Comment by Obihoernchen** [comment]
Finally all todos done :dancer:

Translate go go go :)
