### ISSUE TITLE
[TODO] Gym info window improvements

### ISSUE THREAD

**Issue by Obihoernchen** [brusselopole/Worldopole#97]
**Bugs**
- [X] Fix closing button. See: #96 
- [X] Add arrow to gym. See: #99
- [X] There seem to be a few utf8 issues with gym names. See: https://github.com/brusselopole/Worldopole/commit/9c815f4630456335ef467912781a8c77072b8fc1
- [x] There is dead space right above the gym-info window which is non-clickable and therefore the gym-info can't be closed up there by clicking on the map. See: https://github.com/brusselopole/Worldopole/commit/6fc8f125a54e6d3296f1b8d3b05602a5e71c344e
- [X] Handle gyms without gym-info, right now a lot of them are created on edges of maps where they are updated but gym-info could not be retrieved. Right now the "new" gym-info window is not available for those and ugly info is shown (was it the old of aru.php?). See: #103 

**Ideas**
- [X] Too much empty space? Like wrapping it more, remove "CP" and put CP-Number+IV-Bar closer to the Poké icon, lower inner margins? See: https://github.com/brusselopole/Worldopole/commit/6fc8f125a54e6d3296f1b8d3b05602a5e71c344e
- [X] Move the whole infowindow context from gym_map to gym_defender in `aru.php`? Right now we do things twice.
- [X] Implement gym images with level like: PokemonGoMap/PokemonGo-Map#782. See: #103
- [X] Improve the active/inactive pokemon query. Right now it checks whether last_seen is not older than 24h only. See: ~~https://github.com/brusselopole/Worldopole/commit/4254cfe013b235ea841de14b4f58416dcfc5f792~~ Fixed: 93d4a3575d7a643b8ec0add985b5ecf1a3d2e2df
- [ ] Do we want to add lat long?
- [ ] Replacing gym image with a standard image for gyms without gym info
- [X] Do we want to add a progress bar for level as well? Like this:
```
<=|=|=|==|==|==|===|== |   |   >
Level 7 | Prestige: 434634
```

**Comment by SiteEffect** [comment]
**Bugs**
- Handle gyms without gym-info, right now a lot of them are created on edges of maps where they are updated but gym-info could not be retrieved. Right now the "new" gym-info window is not available for those and ugly info is shown (was it the old of aru.php?) 
- There is dead space right above the gym-info window which is non-clickable and therefore the gym-info can't be closed up there by clicking on the map. See: https://github.com/brusselopole/Worldopole/commit/6fc8f125a54e6d3296f1b8d3b05602a5e71c344e

**Idea**
- Replacing gym image with a standard image for gyms without gym info

Regarding the progress bar, we have to regard the issue that prestige > 50000 is possible which might break the code or at least the bar when we don't address it.

**Comment by SiteEffect** [comment]
#60 should be addressed in this gym-maps overhaul.

**Comment by PoUpA** [comment]
"Move the whole infowindow context from gym_map to gym_defender in aru.php? Right now we do things twice." <== this is not really true. we only query one table so less resources heavy for mysql on a big map. in gym defender we retrieve only one item with many relations and I don't think it's a good idea to do that for every gyms on maps loading.

**Comment by Obihoernchen** [comment]
Almost done guys :+1:

**Comment by Obihoernchen** [comment]
trainer page active gyms fixed: 93d4a3575d7a643b8ec0add985b5ecf1a3d2e2df
